services:
  # --- O CORAÇÃO DO SISTEMA: API (Backend em Go) ---
  api:
    build: .
    container_name: appfitness-backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=admin
      - DB_PASSWORD=password
      - DB_NAME=appfitness_db
      - JWT_SECRET=${JWT_SECRET}       # Melhor usar assim para pegar do .env
      - PORT=8080
      # --- CORREÇÃO AQUI: Passando as variáveis do Asaas para o container ---
      - ASAAS_API_URL=${ASAAS_API_URL}
      - ASAAS_API_KEY=${ASAAS_API_KEY}
    depends_on:
      - postgres
    volumes:
      - ./uploads:/app/uploads
    networks:
      - appfitness-network

  # --- BANCO DE DADOS (PostgreSQL) ---
  postgres:
    image: postgres:14-alpine
    container_name: appfitness-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: appfitness_db
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5432"
    networks:
      - appfitness-network

  # --- GERENCIADOR DO BANCO (Adminer) ---
  adminer:
    image: adminer
    container_name: appfitness-adminer
    restart: always
    ports:
      - "8081:8080"
    networks:
      - appfitness-network

networks:
  appfitness-network:
    driver: bridge